name: build

on: [push]

jobs:
  build-linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
          #sudo apt-get install cython
          echo "target_triplet=`gcc -dumpmachine`" >> $GITHUB_ENV
    - name: fetch libplist
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build.yml
        name: libplist-latest_${{env.target_triplet}}
        path: prebuilt
        repo: nikias/libplist
    - name: install libplist
      run: |
          tar -C prebuilt -xvf prebuilt/libplist.tar
          echo "PREBUILT_PATH=`pwd`/prebuilt" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: autogen
      run: |
          ls -lR ${{env.PREBUILT_PATH}}/usr/local/include
          ./autogen.sh libplist_CFLAGS="-I${{env.PREBUILT_PATH}}/usr/local/include" libplist_LIBS="-L${{env.PREBUILT_PATH}}/usr/local/lib -lplist-2.0"
    - name: make
      run: make V=1
    - name: prepare artifact
      run: |
          mkdir -p dest
          DESTDIR=`pwd`/dest make install
    #- name: publish artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: libusbmuxd-latest_${{env.target_triplet}}
    #    path: dest/*
#  build-macOS:
#    runs-on: macOS-latest
#    steps:
#    - name: install dependencies
#      run: |
#          if test -x "`which port`"; then
#            sudo port install libtool autoconf automake
#          else
#            brew install libtool autoconf automake
#          fi
#          pip install cython
#      shell: bash
#    - uses: actions/checkout@v2
#    - name: autogen
#      run: ./autogen.sh
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#  build-windows:
#    runs-on: windows-latest
#    defaults:
#      run:
#        shell: msys2 {0}
#    steps:
#    - uses: msys2/setup-msys2@v2
#      with:
#        release: false
#        update: false
#        install: >-
#          base-devel
#          git
#          mingw-w64-x86_64-gcc
#          make
#          libtool
#          autoconf
#          automake-wrapper
#    - uses: actions/checkout@v2
#    - name: autogen
#      run: ./autogen.sh CC=gcc CXX=g++ --without-cython
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: print test logs
#      run: |
#          for I in test/*.trs; do
#            RES=`grep ":test-result" $I |cut -d ":" -f 3`
#            if test $RES != PASS; then
#              TESTNAME=`basename $I .trs`
#              echo $TESTNAME:
#              cat test/$TESTNAME.log
#              echo
#            fi
#          done
#      shell: bash
