name: build

on: [push]

jobs:
  build-linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
          echo "target_triplet=`gcc -dumpmachine`" >> $GITHUB_ENV
    - name: fetch libplist
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build.yml
        name: libplist-latest_${{env.target_triplet}}
        repo: nikias/libplist
    - name: install external dependencies
      run: |
          for I in *.tar; do
            sudo tar -C / -xvf $I
          done
          sudo ldconfig
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: autogen
      run: ./autogen.sh PKG_CONFIG_PATH=/usr/local/lib/pkgconfig LDFLAGS="-Wl,-rpath=/usr/local/lib"
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: prepare artifact
      run: |
          mkdir -p dest
          DESTDIR=`pwd`/dest make install
          tar -C dest -cf libusbmuxd.tar usr
    - name: publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: libusbmuxd-latest_${{env.target_triplet}}
        path: libusbmuxd.tar
  build-macOS:
    runs-on: macOS-latest
    steps:
    - name: install dependencies
      run: |
          if test -x "`which port`"; then
            sudo port install libtool autoconf automake pkgconfig
          else
            brew install libtool autoconf automake pkgconfig
          fi
          pip install cython
      shell: bash
    - name: fetch libplist
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build.yml
        name: libplist-latest_macOS
        repo: nikias/libplist
    - name: install external dependencies
      run: |
          for I in *.tar; do
            sudo tar -C / -xvf $I
          done
    - uses: actions/checkout@v2
    - name: autogen
      run: ./autogen.sh PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: prepare artifact
      run: |
          mkdir -p dest
          DESTDIR=`pwd`/dest make install
          tar -C dest -cf libusbmuxd.tar usr
    - name: publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: libusbmuxd-latest_macOS
        path: libusbmuxd.tar
#  build-windows:
#    runs-on: windows-latest
#    defaults:
#      run:
#        shell: msys2 {0}
#    steps:
#    - uses: msys2/setup-msys2@v2
#      with:
#        release: false
#        update: false
#        install: >-
#          base-devel
#          git
#          mingw-w64-x86_64-gcc
#          make
#          libtool
#          autoconf
#          automake-wrapper
#    - uses: actions/checkout@v2
#    - name: autogen
#      run: ./autogen.sh CC=gcc CXX=g++ --without-cython
#    - name: make
#      run: make
