name: build

on: [push]

jobs:
  build-linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
          #sudo apt-get install cython
          echo "target_triplet=`gcc -dumpmachine`" >> $GITHUB_ENV
    - name: install prebuilt dependencies
      run: |
          libplist_artifacts_url=$(curl -fs -H 'Accept: application/vnd.github.antiope-preview+json' https://api.github.com/repos/nikias/libplist/actions/workflows/build.yml/runs \
              | jq "[.workflow_runs[] | select(.name == \"build\")][0].artifacts_url")
          echo libplist_artifacts_url
          if test -z "$libplist_artifacts_url" -o "$libplist_artifacts_url" == "null"; then
            echo "ERROR: Could not get libplist artifacts URL"
            exit 1
          fi
          libplist_artifact_dl_url="$(curl -s -H 'Accept: application/vnd.github.antiope-preview+json' $libplist_artifacts_url \
              | jq "[.artifacts[] | select(.name == \"libplist-latest_${{env.target_triplet}}\").archive_download_url")
          if test -z "$libplist_artifact_dl_url" -o "$libplist_artifact_dl_url" == "null"; then
            echo "ERROR: Could not get artifact archive download URL for ${{env.target_triplet}}"
            exit 1
          fi
          echo "Download URL for ${{env.target_triplet}}: $libplist_artifact_dl_url"
    #- uses: actions/checkout@v2
    #  with:
    #    fetch-depth: 0
    #- name: autogen
    #  run: ./autogen.sh
    #- name: make
    #  run: make
    #- name: prepare artifact
    #  run: |
    #      mkdir -p dest
    #      DESTDIR=`pwd`/dest make install
    #- name: publish artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: libusbmuxd-latest_${{env.target_triplet}}
    #    path: dest/*
#  build-macOS:
#    runs-on: macOS-latest
#    steps:
#    - name: install dependencies
#      run: |
#          if test -x "`which port`"; then
#            sudo port install libtool autoconf automake
#          else
#            brew install libtool autoconf automake
#          fi
#          pip install cython
#      shell: bash
#    - uses: actions/checkout@v2
#    - name: autogen
#      run: ./autogen.sh
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#  build-windows:
#    runs-on: windows-latest
#    defaults:
#      run:
#        shell: msys2 {0}
#    steps:
#    - uses: msys2/setup-msys2@v2
#      with:
#        release: false
#        update: false
#        install: >-
#          base-devel
#          git
#          mingw-w64-x86_64-gcc
#          make
#          libtool
#          autoconf
#          automake-wrapper
#    - uses: actions/checkout@v2
#    - name: autogen
#      run: ./autogen.sh CC=gcc CXX=g++ --without-cython
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: print test logs
#      run: |
#          for I in test/*.trs; do
#            RES=`grep ":test-result" $I |cut -d ":" -f 3`
#            if test $RES != PASS; then
#              TESTNAME=`basename $I .trs`
#              echo $TESTNAME:
#              cat test/$TESTNAME.log
#              echo
#            fi
#          done
#      shell: bash
